[project]
name = "llama-cpp-beam-search"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]
authors = [{ name = "Benedikt Kantz", email = "benedikt.kantz@tugraz.at" }]
license = "MIT"

[project.urls]
Repository = "https://github.com/Dakantz/CHASTE"


[tool.uv]
package = true

[project.scripts]
tex-typst-helper = "texty_tool.main:app"
texty-tool = "texty_tool.main:app"
